const state = {
  showLeftMenu: true,
  globalLoading: true,
  showContral:false,
  menus: [],
  rules: [],
  users: {},
  userGroups: [],
  organizes: [],
  device: {},
  devices:[],
  ac_breed:[],
  light_breed:[],
  led_breed:[],
  record:[],
  countryArr:[],
  address:[],
  floor:[],
  room:[],
  warn:0,
  recordLoading:true,
  maxid:"",
  showHotel:false,
  showFloor:false,
  showRoom:false,
}

export default state
